'use client';
import {useEffect,useMemo,useState} from 'react';
type Paper={id:string,title:string,summary:string,authors:string[],publishedAt:string,upvotes:number,url:string,pdf:string,organization?:{name:string;avatar?:string}|null};
const domains=[['all','All fields','A wide scan across physical intelligence'],['robots','Robots','General-purpose machines that sense and act'],['drones','Drones','Aerial perception, planning and control'],['autonomy','Autonomy','Navigation, driving and decision systems'],['manipulation','Manipulation','Grasping, dexterity and contact-rich control'],['embodied','Embodied AI','Agents grounded in bodies and environments'],['simulation','Simulation','World models, digital twins and sim-to-real']];
const fallback:Paper[]=[
{id:'2406.09246',title:'OpenVLA: An Open-Source Vision-Language-Action Model',summary:'A generalist policy that turns visual observations and language instructions into robot actions, trained on a large mixture of manipulation data.',authors:['Moo Jin Kim','Karl Pertsch','Siddharth Karamcheti'],publishedAt:'2024-06-13',upvotes:412,url:'https://huggingface.co/papers/2406.09246',pdf:'https://arxiv.org/pdf/2406.09246',organization:{name:'Stanford & collaborators'}},
{id:'2306.10007',title:'Robot Learning with Sensorimotor Pre-training',summary:'Self-supervised pre-training over interleaved images, proprioception and actions for scalable robot learning.',authors:['Ilija Radosavovic','Baifeng Shi','Letian Fu'],publishedAt:'2023-06-16',upvotes:173,url:'https://huggingface.co/papers/2306.10007',pdf:'https://arxiv.org/pdf/2306.10007',organization:{name:'Meta AI Research'}},
{id:'2302.11550',title:'Learning Agile Flight in the Wild',summary:'An autonomous quadrotor learns high-speed flight through complex natural environments using onboard sensing and policy learning.',authors:['Davide Scaramuzza et al.'],publishedAt:'2023-02-22',upvotes:108,url:'https://huggingface.co/papers/2302.11550',pdf:'https://arxiv.org/pdf/2302.11550',organization:{name:'University of Zurich'}}];
export default function Home(){const[domain,setDomain]=useState('all');const[view,setView]=useState<'domains'|'labs'>('domains');const[q,setQ]=useState('');const[papers,setPapers]=useState<Paper[]>(fallback);const[loading,setLoading]=useState(false);const[source,setSource]=useState('Curated starter set');
useEffect(()=>{if(location.hash==='#labs')setView('labs')},[]);
useEffect(()=>{let live=true;setLoading(true);fetch(`/api/papers?domain=${domain}${q?`&q=${encodeURIComponent(q)}`:''}`).then(r=>r.json()).then(d=>{if(live&&d.papers?.length){setPapers(d.papers);setSource(d.source)}}).finally(()=>live&&setLoading(false));return()=>{live=false}},[domain,q]);
const featured=papers[0]||fallback[0];const stats=useMemo(()=>({papers:papers.length,domains:domains.length-1,labs:new Set(papers.map(p=>p.organization?.name||'Independent & cross-lab')).size}),[papers]);
const labs=useMemo(()=>Object.entries(papers.reduce<Record<string,Paper[]>>((acc,p)=>{const key=p.organization?.name||'Independent & cross-lab';(acc[key]??=[]).push(p);return acc},{})).sort((a,b)=>b[1].length-a[1].length),[papers]);
return <main><header><a className="brand" href="#">PHYSICAL<span>ATLAS</span></a><nav><button onClick={()=>setView('domains')} className={view==='domains'?'selected':''}>DOMAINS</button><button onClick={()=>setView('labs')} className={view==='labs'?'selected':''}>LABS</button><a href="#papers">LATEST</a><a href="#method">METHOD</a></nav><div className="source">LIVE INDEX <i/></div></header>
<section className="hero"><div className="eyebrow">A LIVING INDEX OF PHYSICAL INTELLIGENCE</div><h1>Research that<br/><em>moves</em> the world.</h1><p>Find the papers shaping robots, drones, autonomous systems and embodied agents. Browse by field or see which labs are moving the frontier.</p><div className="search"><span>⌕</span><input aria-label="Search papers" placeholder="Search methods, tasks, authors…" value={q} onChange={e=>setQ(e.target.value)}/><kbd>LIVE</kbd></div></section>
<section className="numbers"><div><b>{stats.papers||'—'}</b><span>papers in view</span></div><div><b>{view==='labs'?stats.labs:stats.domains}</b><span>{view==='labs'?'labs in view':'research domains'}</span></div><div><b>{source}</b><span>current source</span></div></section>
<div className="viewSwitch"><button onClick={()=>setView('domains')} className={view==='domains'?'active':''}>Explore by domain</button><button onClick={()=>setView('labs')} className={view==='labs'?'active':''}>Explore by lab</button></div>
{view==='domains'?<section className="domains" id="domains"><div className="sectionhead"><span>01 / FIELD MAP</span><h2>Explore by domain</h2></div><div className="domainGrid">{domains.map(([id,name,desc],i)=><button key={id} onClick={()=>{setQ('');setDomain(id)}} className={domain===id?'active':''}><small>{String(i+1).padStart(2,'0')}</small><strong>{name}</strong><p>{desc}</p><span>→</span></button>)}</div></section>:
<section className="labs" id="labs"><div className="sectionhead"><span>01 / LAB MAP</span><h2>Explore by lab</h2></div><p className="labNote">Labs come from organization metadata attached to public paper records. Papers without an affiliation stay visible in Independent & cross-lab instead of being guessed.</p><div className="labGrid">{labs.map(([name,items],i)=><article key={name}><div className="labTop"><small>{String(i+1).padStart(2,'0')}</small><b>{items.length} {items.length===1?'PAPER':'PAPERS'}</b></div><h3>{name}</h3><div>{items.slice(0,3).map(p=><a key={p.id} href={p.url} target="_blank"><span>{p.title}</span><i>↗</i></a>)}</div></article>)}</div></section>}
<section className="feature"><div className="featureMeta"><span>02 / SIGNAL</span><b>MOST RELEVANT NOW</b></div><article><div><div className="tag">{domain==='all'?'PHYSICAL AI':domain.toUpperCase()}</div><h2>{featured.title}</h2><p>{featured.summary}</p><div className="authors">{featured.authors?.join(' · ')}</div><a href={featured.url} target="_blank">READ PAPER ↗</a></div><div className="orb"><span>{featured.id}</span><div>φ</div><small>SENSE<br/>THINK<br/>ACT</small></div></article></section>
<section className="papers" id="papers"><div className="sectionhead"><span>03 / RESEARCH FEED</span><h2>{loading?'Scanning the field…':'Latest papers'}</h2></div><div className="paperList">{papers.slice(0,12).map((p,i)=><a key={p.id} href={p.url} target="_blank"><span className="rank">{String(i+1).padStart(2,'0')}</span><div><h3>{p.title}</h3><p>{p.summary}</p><small>{p.authors?.slice(0,3).join(', ')}{p.organization?.name?` · ${p.organization.name}`:''}</small></div><div className="paperMeta"><b>{p.upvotes||'NEW'}</b><small>{p.publishedAt?.slice(0,10)}</small><span>↗</span></div></a>)}</div></section>
<section className="method" id="method"><span>HOW IT WORKS</span><h2>A research radar,<br/>not another reading list.</h2><div><p><b>01</b>Discover from public research indexes and canonical paper records.</p><p><b>02</b>Browse by Physical AI domain or reported research organization.</p><p><b>03</b>Use optional Jev evaluation for fast, typed classification with explicit confidence.</p></div></section>
<footer><div className="brand">PHYSICAL<span>ATLAS</span></div><p>Built from public research metadata. Paper rights remain with their authors and publishers.</p><a href="https://huggingface.co/docs/hub/en/api" target="_blank">DATA SOURCES ↗</a></footer></main>}
