export type CuratedLab={
  name:string; kind:'Research lab'|'Physical AI company'|'Open research infrastructure';
  focus:string[]; why:string; source:string; sourceLabel:string;
  papers:{title:string;url:string;year:string}[];
};

// Editorial shortlist, not a universal ranking. Every entry links to a primary
// research/publication source. Product or funding claims are not ranking inputs.
export const curatedLabs:CuratedLab[]=[
 {name:'Google DeepMind Robotics',kind:'Research lab',focus:['embodied AI','manipulation','generalist agents'],why:'Sustained primary work on robot foundation models, large-scale real-world data and generalist manipulation.',source:'https://deepmind.google/research/publications/48151/',sourceLabel:'Official publication archive',papers:[{title:'AutoRT: Embodied Foundation Models for Large Scale Orchestration',url:'https://deepmind.google/research/publications/48151/',year:'2024'},{title:'RoboCat: A Self-Improving Foundation Agent for Robotic Manipulation',url:'https://deepmind.google/research/publications/35829/',year:'2023'},{title:'RT-1: Robotics Transformer for Real-World Control at Scale',url:'https://arxiv.org/abs/2212.06817',year:'2022'},{title:'RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control',url:'https://arxiv.org/abs/2307.15818',year:'2023'},{title:'Open X-Embodiment: Robotic Learning Datasets and RT-X Models',url:'https://arxiv.org/abs/2310.08864',year:'2023'}]},
 {name:'Google Research',kind:'Research lab',focus:['language-conditioned robotics','embodied AI','affordance grounding'],why:'Official projects index filtered to Physical AI: PaLM-SayCan grounded a large language model in real robot affordances on Everyday Robots hardware.',source:'https://research.google/resources/our-projects/',sourceLabel:'Official projects index (Physical AI filtered)',papers:[{title:'Do As I Can, Not As I Say: Grounding Language in Robotic Affordances',url:'https://arxiv.org/abs/2204.01691',year:'2022'},{title:'PaLM-SayCan project page',url:'https://sites.research.google/palm-saycan',year:'Live'}]},
 {name:'Physical Intelligence',kind:'Physical AI company',focus:['vision-language-action','robot learning','manipulation'],why:'A research-first company publishing generalist policies trained across robots and tasks.',source:'https://www.pi.website/research',sourceLabel:'Official research index',papers:[{title:'π0: A Vision-Language-Action Flow Model for General Robot Control',url:'https://www.pi.website/blog/pi0',year:'2024'},{title:'FAST: Efficient Robot Action Tokenization',url:'https://www.pi.website/research/fast',year:'2024'},{title:'Teaching Robots to Listen and Think Harder',url:'https://www.pi.website/research/hirobot',year:'2025'},{title:'Emergence of Human to Robot Transfer in VLAs',url:'https://www.pi.website/research/human_to_robot',year:'2025'},{title:'VLAs that Train Fast, Run Fast, and Generalize Better',url:'https://www.pi.website/research/knowledge_insulation',year:'2025'},{title:'VLAs with Long and Short-Term Memory',url:'https://www.pi.website/research/memory',year:'2025'},{title:'Real-Time Action Chunking with Large Models',url:'https://www.pi.website/research/real_time_chunking',year:'2025'},{title:'Precise Manipulation with Efficient Online RL',url:'https://www.pi.website/research/rlt',year:'2025'}]},
 {name:'NVIDIA Robotics Research',kind:'Research lab',focus:['simulation','robot learning','sim-to-real'],why:'Primary research and open systems connecting scalable simulation, training and physical deployment.',source:'https://research.nvidia.com/publications',sourceLabel:'Official NVIDIA Research publications',papers:[{title:'Isaac Lab: A GPU-Accelerated Simulation Framework for Robot Learning',url:'https://arxiv.org/abs/2511.04831',year:'2025'},{title:'NVIDIA Isaac Sim: Enabling Scalable GPU-Accelerated Simulation for Robotics',url:'https://arxiv.org/abs/2606.03551',year:'2026'}]},
 {name:'Toyota Research Institute Robotics',kind:'Research lab',focus:['large behavior models','dexterous manipulation','human assistance'],why:'Long-running real-world robotics program with a public publication archive and current manipulation work.',source:'https://www.tri.global/publications',sourceLabel:'Official publication archive',papers:[{title:'A Careful Examination of Large Behavior Models for Multitask Dexterous Manipulation',url:'https://doi.org/10.48550/arXiv.2507.05331',year:'2025'},{title:'Diffusion Policy: Visuomotor Policy Learning via Action Diffusion',url:'https://arxiv.org/abs/2303.04137',year:'2023'},{title:'Dreamitate: Real-World Visuomotor Policy Learning via Video Generation',url:'https://www.tri.global/research/dreamitate-real-world-visuomotor-policy-learning-video-generation',year:'2026'}]},
 {name:'Stanford REAL',kind:'Research lab',focus:['robot learning','foundation models','manipulation'],why:'University lab producing influential open models, datasets and evaluation for generalist robot learning.',source:'https://real.stanford.edu/',sourceLabel:'Official lab and publications',papers:[{title:'OpenVLA: An Open-Source Vision-Language-Action Model',url:'https://arxiv.org/abs/2406.09246',year:'2024'},{title:'Learning Fine-Grained Bimanual Manipulation with Low-Cost Hardware',url:'https://arxiv.org/abs/2304.13705',year:'2023'}]},
 {name:'Berkeley RAIL',kind:'Research lab',focus:['robot learning','manipulation','reinforcement learning'],why:'Deep publication record spanning learning-based control, dexterity and generalization.',source:'https://rail.eecs.berkeley.edu/publications.html',sourceLabel:'Official publication archive',papers:[{title:'DexterityGen: Foundation Controller for Unprecedented Dexterity',url:'https://arxiv.org/abs/2502.04307',year:'2025'},{title:'BridgeData V2: A Dataset for Robot Learning at Scale',url:'https://arxiv.org/abs/2308.12952',year:'2023'}]},
 {name:'CMU Robotics Institute',kind:'Research lab',focus:['autonomy','field robotics','manipulation'],why:'Broad, long-running institute with primary work across autonomous vehicles, field systems and robot learning.',source:'https://publications.ri.cmu.edu/',sourceLabel:'Official publication archive',papers:[{title:'Robotics Institute Publications Archive',url:'https://publications.ri.cmu.edu/',year:'Live'}]},
 {name:'MIT CSAIL Robotics',kind:'Research lab',focus:['robot learning','planning','distributed robotics'],why:'Multiple active robotics groups backed by a first-party institute publication index.',source:'https://publications.csail.mit.edu/',sourceLabel:'Official publication archive',papers:[{title:'CSAIL Publications',url:'https://publications.csail.mit.edu/',year:'Live'}]},
 {name:'ETH Zürich Robotic Systems Lab',kind:'Research lab',focus:['legged robots','locomotion','field autonomy'],why:'Strong physical-system evidence in locomotion, navigation and mobile manipulation.',source:'https://rsl.ethz.ch/publications-sources.html',sourceLabel:'Official publication archive',papers:[{title:'Learning Robust Autonomous Navigation and Locomotion for Wheeled-Legged Robots',url:'https://arxiv.org/abs/2405.01792',year:'2024'}]},
 {name:'UPenn GRASP Lab',kind:'Research lab',focus:['drones','multi-robot systems','perception'],why:'Foundational and current primary research in aerial robotics, autonomy and sensing.',source:'https://www.grasp.upenn.edu/publications/',sourceLabel:'Official publication archive',papers:[{title:'Autonomous Micro UAVs',url:'https://www.grasp.upenn.edu/projects/autonomous-micro-uavs/',year:'Live'}]},
 {name:'UZH Robotics and Perception Group',kind:'Research lab',focus:['drones','agile flight','event vision'],why:'Peer-reviewed work grounded in high-speed autonomous flight and onboard perception.',source:'https://rpg.ifi.uzh.ch/publications.html',sourceLabel:'Official publication archive',papers:[{title:'Learning High-Speed Flight in the Wild',url:'https://rpg.ifi.uzh.ch/docs/Loquercio21_Science.pdf',year:'2021'},{title:'Learning Quadrotor Control From Visual Features Using Differentiable Simulation',url:'https://rpg.ifi.uzh.ch/docs/ICRA25_Heeg.pdf',year:'2025'},{title:'Dream to Fly: Model-Based Reinforcement Learning for Vision-Based Drone Flight',url:'https://rpg.ifi.uzh.ch/docs/ICRA26_Romero.pdf',year:'2026'},{title:'Learning Agile Quadrotor Flight in the Real World',url:'https://rpg.ifi.uzh.ch/docs/RSS26_Ren.pdf',year:'2026'}]},
 {name:'Skild AI',kind:'Physical AI company',focus:['omni-bodied policies','locomotion','robot foundation models'],why:'Publishes technical results for one policy spanning different robots and real-world settings.',source:'https://www.skild.ai/blogs/one-policy-all-scenarios',sourceLabel:'Official technical research post',papers:[{title:'One Model, Any Scenario: End-to-end Locomotion from Vision',url:'https://www.skild.ai/blogs/one-policy-all-scenarios',year:'2025'},{title:'S1: In-Context Learning for Robotics',url:'https://www.skild.ai/blogs/s1',year:'2026'},{title:'Learning by Watching Human Videos',url:'https://www.skild.ai/blogs/learning-by-watching',year:'2026'}]},
 {name:'Figure AI',kind:'Physical AI company',focus:['humanoids','vision-language-action','full-body control'],why:'Publishes technical system details and real-world evaluations for generalist humanoid control.',source:'https://www.figure.ai/news/helix',sourceLabel:'Official technical report',papers:[{title:'Helix: A Vision-Language-Action Model for Generalist Humanoid Control',url:'https://www.figure.ai/news/helix',year:'2025'},{title:'Scaling Helix: A New State of the Art in Humanoid Logistics',url:'https://www.figure.ai/news/scaling-helix-logistics',year:'2025'},{title:'Project Go-Big: Internet-Scale Humanoid Pretraining and Direct Human-to-Robot Transfer',url:'https://www.figure.ai/news/project-go-big',year:'2025'},{title:'Introducing Helix 02: Full-Body Autonomy',url:'https://www.figure.ai/news/helix-02',year:'2026'}]},
 {name:'1X World Model Lab',kind:'Physical AI company',focus:['world models','humanoids','video-to-action'],why:'A dedicated lab publishing a technical report and evaluation work on predictive models for robot learning.',source:'https://www.1x.tech/discover/1x-world-model-lab',sourceLabel:'Official lab page',papers:[{title:'1X World Model: Evaluating Bits, not Atoms',url:'https://www.1x.tech/1x-world-model.pdf',year:'2025'},{title:"NEO's Hands: An API to the Physical World",url:'https://www.1x.tech/discover/neos-hands',year:'2026'}]},
 {name:'Waymo Research',kind:'Research lab',focus:['autonomy','motion planning','safety'],why:'Primary publication program grounded in large-scale deployed autonomous driving and safety measurement.',source:'https://waymo.com/research/',sourceLabel:'Official research archive',papers:[{title:'Waymo Research Publications',url:'https://waymo.com/research/',year:'Live'},{title:'VectorNet: Encoding HD Maps and Agent Dynamics from Vectorized Representation',url:'https://arxiv.org/abs/2005.04259',year:'2020'}]},
 {name:'FieldAI Research Institute',kind:'Research lab',focus:['field robotics','embodied reasoning','cross-platform autonomy'],why:'Publishes primary research on autonomy and embodied agents for unstructured environments.',source:'https://www.fieldai.com/fairi',sourceLabel:'Official institute page',papers:[{title:'Enter the Mind Palace: Long-term Active Embodied Question Answering',url:'https://arxiv.org/abs/2507.12846',year:'2025'}]},
 {name:'Hugging Face LeRobot',kind:'Open research infrastructure',focus:['open-source robotics','datasets','robot learning'],why:'Open tools, datasets and paper collections that make reproducible robot learning easier; listed as infrastructure, not a frontier lab.',source:'https://huggingface.co/lerobot/papers',sourceLabel:'Official paper collection',papers:[{title:'LeRobot: An Open-Source Library for End-to-End Robot Learning',url:'https://arxiv.org/abs/2602.22818',year:'2026'}]},
 {name:'Prime Intellect',kind:'Open research infrastructure',focus:['distributed training','open agents','compute'],why:'Important open training infrastructure and research, but its published evidence is currently AI training rather than physical-system research; included as an adjacent enabler, not ranked as a Physical AI lab.',source:'https://www.primeintellect.ai/blog',sourceLabel:'Official research and release index',papers:[{title:'INTELLECT-2: Globally Distributed Reinforcement Learning',url:'https://www.primeintellect.ai/blog/intellect-2',year:'2025'}]}
];

export type IndustryContribution={
  area:string; contribution:string; papers:string[]; kind:'Open-source'|'Commercial product'|'Deployed system'|'Platform/tooling';
};

export const industryContributions:IndustryContribution[]=[
  {area:'Robot simulation and synthetic data',contribution:'Gave industry a physics-accurate, GPU-parallel simulation and synthetic-data pipeline (digital twins, domain randomization, RL training) that is now a standard pre-deployment validation step for manipulation, mobile, and warehouse robotics.',papers:['NVIDIA Isaac Sim','NVIDIA Isaac Lab'],kind:'Platform/tooling'},
  {area:'Open robot-learning stack',contribution:'Standardized datasets, imitation and RL policies, teleoperation data collection, and low-cost hardware integration in one open library, letting startups and factories build custom robot skills without proprietary infrastructure.',papers:['LeRobot'],kind:'Open-source'},
  {area:'Open vision-language-action models',contribution:'Released 7B-parameter open-weight VLA models fine-tunable on consumer GPUs for hundreds of dollars, giving companies an affordable path to adapt generalist manipulation policies to their own tasks and embodiments.',papers:['OpenVLA'],kind:'Open-source'},
  {area:'Driverless mobility as a service',contribution:'Proved full-stack urban autonomy in revenue-generating service, establishing the safety case, fleet operations, and HD-mapping pipelines required to commercialize driverless vehicles.',papers:['Waymo autonomy'],kind:'Deployed system'},
  {area:'VLA-controlled humanoids in manufacturing',contribution:'Demonstrated an onboard dual-speed neural policy (fast reflexes plus slow reasoning) operating a commercial humanoid on logistics tasks in a real automotive factory pilot.',papers:['Figure AI Helix'],kind:'Deployed system'},
  {area:'Licensed generalist manipulation foundation models',contribution:'Introduced flow-matching action generation in a VLA trained on large multi-robot data, offered as a licensable foundation robot brain adaptable to dexterous tasks such as laundry folding and table bussing.',papers:['π0 (Physical Intelligence)'],kind:'Commercial product'},
  {area:'Cross-embodiment robot brain',contribution:'Showed a single learned policy running across radically different robot bodies from drones to quadrupeds, sold commercially so customers buy general capability per robot rather than per-task software.',papers:['Skild AI one-policy'],kind:'Commercial product'},
  {area:'Fleet-scale autonomous data collection',contribution:'Orchestrated LLM-directed fleets of mobile manipulators that autonomously selected and executed diverse tasks in real office buildings under constitutional-style safety filtering, establishing the data flywheel and safety scaffolding industry now uses for large-scale robot data collection.',papers:['AutoRT','RoboCat'],kind:'Deployed system'},
  {area:'World models for humanoid evaluation',contribution:'Provided video-generation world models that let teams test humanoid policies against rare and hazardous scenarios in simulation before risking hardware, cutting validation cost for commercial deployments.',papers:['1X World Model'],kind:'Platform/tooling'},
];
