export type CuratedLab={
  name:string; kind:'Research lab'|'Physical AI company'|'Open research infrastructure';
  focus:string[]; why:string; source:string; sourceLabel:string;
  papers:{title:string;url:string;year:string}[];
};

// Editorial shortlist, not a universal ranking. Every entry links to a primary
// research/publication source. Product or funding claims are not ranking inputs.
export const curatedLabs:CuratedLab[]=[
 {name:'Google DeepMind Robotics',kind:'Research lab',focus:['embodied AI','manipulation','generalist agents'],why:'Sustained primary work on robot foundation models, large-scale real-world data and generalist manipulation.',source:'https://deepmind.google/research/publications/48151/',sourceLabel:'Official publication archive',papers:[{title:'AutoRT: Embodied Foundation Models for Large Scale Orchestration',url:'https://deepmind.google/research/publications/48151/',year:'2024'},{title:'RoboCat: A Self-Improving Foundation Agent for Robotic Manipulation',url:'https://deepmind.google/research/publications/35829/',year:'2023'}]},
 {name:'Physical Intelligence',kind:'Physical AI company',focus:['vision-language-action','robot learning','manipulation'],why:'A research-first company publishing generalist policies trained across robots and tasks.',source:'https://www.pi.website/research',sourceLabel:'Official research index',papers:[{title:'π0: A Vision-Language-Action Flow Model for General Robot Control',url:'https://www.pi.website/blog/pi0',year:'2024'}]},
 {name:'NVIDIA Robotics Research',kind:'Research lab',focus:['simulation','robot learning','sim-to-real'],why:'Primary research and open systems connecting scalable simulation, training and physical deployment.',source:'https://research.nvidia.com/publications',sourceLabel:'Official NVIDIA Research publications',papers:[{title:'Isaac Lab: A GPU-Accelerated Simulation Framework for Robot Learning',url:'https://arxiv.org/abs/2511.04831',year:'2025'},{title:'NVIDIA Isaac Sim: Enabling Scalable GPU-Accelerated Simulation for Robotics',url:'https://arxiv.org/abs/2606.03551',year:'2026'}]},
 {name:'Toyota Research Institute Robotics',kind:'Research lab',focus:['large behavior models','dexterous manipulation','human assistance'],why:'Long-running real-world robotics program with a public publication archive and current manipulation work.',source:'https://www.tri.global/publications',sourceLabel:'Official publication archive',papers:[{title:'A Careful Examination of Large Behavior Models for Multitask Dexterous Manipulation',url:'https://doi.org/10.48550/arXiv.2507.05331',year:'2025'},{title:'Dreamitate: Real-World Visuomotor Policy Learning via Video Generation',url:'https://www.tri.global/research/dreamitate-real-world-visuomotor-policy-learning-video-generation',year:'2026'}]},
 {name:'Stanford REAL',kind:'Research lab',focus:['robot learning','foundation models','manipulation'],why:'University lab producing influential open models, datasets and evaluation for generalist robot learning.',source:'https://real.stanford.edu/',sourceLabel:'Official lab and publications',papers:[{title:'OpenVLA: An Open-Source Vision-Language-Action Model',url:'https://arxiv.org/abs/2406.09246',year:'2024'}]},
 {name:'Berkeley RAIL',kind:'Research lab',focus:['robot learning','manipulation','reinforcement learning'],why:'Deep publication record spanning learning-based control, dexterity and generalization.',source:'https://rail.eecs.berkeley.edu/publications.html',sourceLabel:'Official publication archive',papers:[{title:'DexterityGen: Foundation Controller for Unprecedented Dexterity',url:'https://arxiv.org/abs/2502.04307',year:'2025'}]},
 {name:'CMU Robotics Institute',kind:'Research lab',focus:['autonomy','field robotics','manipulation'],why:'Broad, long-running institute with primary work across autonomous vehicles, field systems and robot learning.',source:'https://publications.ri.cmu.edu/',sourceLabel:'Official publication archive',papers:[{title:'Robotics Institute Publications Archive',url:'https://publications.ri.cmu.edu/',year:'Live'}]},
 {name:'MIT CSAIL Robotics',kind:'Research lab',focus:['robot learning','planning','distributed robotics'],why:'Multiple active robotics groups backed by a first-party institute publication index.',source:'https://publications.csail.mit.edu/',sourceLabel:'Official publication archive',papers:[{title:'CSAIL Publications',url:'https://publications.csail.mit.edu/',year:'Live'}]},
 {name:'ETH Zürich Robotic Systems Lab',kind:'Research lab',focus:['legged robots','locomotion','field autonomy'],why:'Strong physical-system evidence in locomotion, navigation and mobile manipulation.',source:'https://rsl.ethz.ch/publications-sources.html',sourceLabel:'Official publication archive',papers:[{title:'Learning Robust Autonomous Navigation and Locomotion for Wheeled-Legged Robots',url:'https://arxiv.org/abs/2405.01792',year:'2024'}]},
 {name:'UPenn GRASP Lab',kind:'Research lab',focus:['drones','multi-robot systems','perception'],why:'Foundational and current primary research in aerial robotics, autonomy and sensing.',source:'https://www.grasp.upenn.edu/publications/',sourceLabel:'Official publication archive',papers:[{title:'Autonomous Micro UAVs',url:'https://www.grasp.upenn.edu/projects/autonomous-micro-uavs/',year:'Live'}]},
 {name:'UZH Robotics and Perception Group',kind:'Research lab',focus:['drones','agile flight','event vision'],why:'Peer-reviewed work grounded in high-speed autonomous flight and onboard perception.',source:'https://rpg.ifi.uzh.ch/publications.html',sourceLabel:'Official publication archive',papers:[{title:'Learning High-Speed Flight in the Wild',url:'https://rpg.ifi.uzh.ch/docs/Loquercio21_Science.pdf',year:'2021'}]},
 {name:'Skild AI',kind:'Physical AI company',focus:['omni-bodied policies','locomotion','robot foundation models'],why:'Publishes technical results for one policy spanning different robots and real-world settings.',source:'https://www.skild.ai/blogs/one-policy-all-scenarios',sourceLabel:'Official technical research post',papers:[{title:'One Model, Any Scenario: End-to-end Locomotion from Vision',url:'https://www.skild.ai/blogs/one-policy-all-scenarios',year:'2025'},{title:'S1: In-Context Learning for Robotics',url:'https://www.skild.ai/blogs/s1',year:'2026'}]},
 {name:'Figure AI',kind:'Physical AI company',focus:['humanoids','vision-language-action','full-body control'],why:'Publishes technical system details and real-world evaluations for generalist humanoid control.',source:'https://www.figure.ai/news/helix',sourceLabel:'Official technical report',papers:[{title:'Helix: A Vision-Language-Action Model for Generalist Humanoid Control',url:'https://www.figure.ai/news/helix',year:'2025'}]},
 {name:'1X World Model Lab',kind:'Physical AI company',focus:['world models','humanoids','video-to-action'],why:'A dedicated lab publishing a technical report and evaluation work on predictive models for robot learning.',source:'https://www.1x.tech/discover/1x-world-model-lab',sourceLabel:'Official lab page',papers:[{title:'1X World Model: Evaluating Bits, not Atoms',url:'https://www.1x.tech/1x-world-model.pdf',year:'2025'}]},
 {name:'Waymo Research',kind:'Research lab',focus:['autonomy','motion planning','safety'],why:'Primary publication program grounded in large-scale deployed autonomous driving and safety measurement.',source:'https://waymo.com/research/',sourceLabel:'Official research archive',papers:[{title:'Waymo Research Publications',url:'https://waymo.com/research/',year:'Live'}]},
 {name:'FieldAI Research Institute',kind:'Research lab',focus:['field robotics','embodied reasoning','cross-platform autonomy'],why:'Publishes primary research on autonomy and embodied agents for unstructured environments.',source:'https://www.fieldai.com/fairi',sourceLabel:'Official institute page',papers:[{title:'Enter the Mind Palace: Long-term Active Embodied Question Answering',url:'https://arxiv.org/abs/2507.12846',year:'2025'}]},
 {name:'Hugging Face LeRobot',kind:'Open research infrastructure',focus:['open-source robotics','datasets','robot learning'],why:'Open tools, datasets and paper collections that make reproducible robot learning easier; listed as infrastructure, not a frontier lab.',source:'https://huggingface.co/lerobot/papers',sourceLabel:'Official paper collection',papers:[{title:'LeRobot: An Open-Source Library for End-to-End Robot Learning',url:'https://arxiv.org/abs/2602.22818',year:'2026'}]},
 {name:'Prime Intellect',kind:'Open research infrastructure',focus:['distributed training','open agents','compute'],why:'Important open training infrastructure and research, but its published evidence is currently AI training rather than physical-system research; included as an adjacent enabler, not ranked as a Physical AI lab.',source:'https://www.primeintellect.ai/blog',sourceLabel:'Official research and release index',papers:[{title:'INTELLECT-2: Globally Distributed Reinforcement Learning',url:'https://www.primeintellect.ai/blog/intellect-2',year:'2025'}]}
];
